// <auto-generated />
using System;
using Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(CommonContext))]
    [Migration("20200310100926_0.0.1")]
    partial class _001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Database.Models.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentLevel")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalDepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganaizationId")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganaizationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentDepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("OrganaizationId1");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Common.Database.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<byte[]>("EmployeeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Common.Database.Models.Organaization", b =>
                {
                    b.Property<Guid>("OrganaizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganaizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganaizationId");

                    b.ToTable("Organaization");
                });

            modelBuilder.Entity("Common.Database.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyGlobalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CompanyImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NowFiscalYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("SystemCreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemModifyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Common.Database.Models.Department", b =>
                {
                    b.HasOne("Common.Database.Models.Organaization", "Organaization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganaizationId1");
                });
#pragma warning restore 612, 618
        }
    }
}
